/**
 * Refreshes backend/config/disposable-email-domains.txt from the maintained
 * "disposable-email-domains" list (https://github.com/disposable-email-domains/disposable-email-domains).
 *
 *   npm run disposable:update
 *
 * Then restart the backend. Domains in backend/config/disposable-email-allowlist.txt (one per line)
 * are never blocked, even if the list contains them.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf';
const target = fileURLToPath(new URL('../../config/disposable-email-domains.txt', import.meta.url));

const response = await fetch(SOURCE, { signal: AbortSignal.timeout(30000) });
if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`);
const domains = (await response.text())
  .split(/\r?\n/)
  .map((line) => line.trim().toLowerCase())
  .filter((line) => line && !line.startsWith('#') && /^[a-z0-9.-]+\.[a-z]{2,}$/.test(line));
if (domains.length < 1000) throw new Error(`Only ${domains.length} domains downloaded — refusing to overwrite the list.`);

const header = `# Disposable email domains — generated by npm run disposable:update on ${new Date().toISOString().slice(0, 10)}\n# Source: ${SOURCE}\n`;
writeFileSync(target, header + [...new Set(domains)].sort().join('\n') + '\n');
console.log(`Saved ${domains.length} domains to ${target}`);
